platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
- name: xmage-docker
  path: .
- name: xmage

outputs:
- name: image

caches:
- path: cache

run:
  path: build