platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: xmage-docker
- name: xmage-release
- name: ci

outputs:
- name: xmage

run:
  path: ci/scripts/extract_release.sh