resource_types:
- name: discord-resource
  type: docker-image
  source:
    repository: trivigy/discord-resource

resources:
- name: ci
  type: git
  source:
    uri: https://github.com/tysongg/xmage-ci.git
  icon: gitlab
  check_every: 10m

- name: xmage-docker
  type: git
  source:
    uri: https://github.com/tysongg/docker-xmage-openjdk.git
  icon: gitlab
  check_every: 10m

- name: xmage-release
  type: github-release
  source:
    owner: magefree
    repository: mage
    access_token: ((github-access-token))
    tag_filter: xmage_(.*)
  icon: package-down
  check_every: 10m

- name: xmage-image
  type: registry-image
  source:
    repository: tysondenio/xmage
    username: ((docker-username))
    password: ((docker-password))
  icon: docker
  check_every: 10m

- name: discord
  type: discord-resource
  source: 
    token: ((discord-token))
  check_every: 999999h

jobs:
- name: build
  public: true
  plan:
  - in_parallel:
    - get: xmage-docker
      trigger: true
    - get: xmage-release
      trigger: true
    - get: ci
  - task: Extract Release
    file: ci/tasks/extract_release.yml
  - task: Build Image
    privileged: true
    file: ci/tasks/build_image.yml
  - put: xmage-image
    params: {
      image: image/image.tar,
      additional_tags: xmage-release/version
    }
  - put: discord
    params: {
      channel: 675196181097349120,
      color: 6076508,
      title: A new xmage docker image is avaliable,
      message: https://hub.docker.com/r/tysondenio/xmage/tags
    }