resources:
- name: ci
  type: git
  source:
    uri: https://github.com/tysongg/xmage-ci.git
  icon: gitlab
  check_every: 10m

- name: xmage-docker
  type: git
  source:
    uri: https://github.com/tysongg/docker-xmage-openjdk.git
  icon: gitlab
  check_every: 10m

- name: xmage-release
  type: github-release
  source:
    owner: magefree
    repository: mage
    access_token: ((github-access-token))
    tag_filter: xmage_(.*)
  icon: package-down
  check_every: 10m

# - name: xmage-image
#   type: registry-image
#   source:
#     repository: tysongg/xmage
#     username: ((docker-username))
#     password: ((docker-password))

jobs:
- name: build
  plan:
  - in_parallel:
    - get: xmage-docker
      trigger: true
    - get: xmage-release
      trigger: true
    - get: ci
  - task: Extract Release
    file: ci/tasks/extract_release.yml
  - task: Build Image
    file: ci/tasks/build_image.yml